#Tabla descriptiva de los servicios existentes
##################################################################################################
####################################################ACTUALIZACIÓN 17/07/2025######################
##################################################################################################

manuel <- column(12,
            checkboxInput(inputId = 'atn2_43', 
                         label = 'Medicina nuclear', 
                         value = F),  
            numericInput(inputId = 'atn2_43me',
                       label = '¿Cuántos médicos especialistas trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_43m',
                       label = '¿Cuántos médicos generales trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_43e',
                       label = '¿Cuántos enfermeros trabajan en el servicio?', 
                       value = NA_integer_),
            selectInput(inputId = 'atn2_43eq',
                       label = '¿Cuenta con el equipo para operar el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),

           checkboxInput(inputId = 'atn2_44', 
                         label = 'Medicina familiar', 
                         value = F), 
           numericInput(inputId = 'atn2_44me',
                       label = '¿Cuántos médicos especialistas trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_44m',
                       label = '¿Cuántos médicos generales trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_44e',
                       label = '¿Cuántos enfermeros trabajan en el servicio?', 
                       value = NA_integer_),
            selectInput(inputId = 'atn2_44eq',
                       label = '¿Cuenta con el equipo para operar el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),

           checkboxInput(inputId = 'atn2_45', 
                         label = 'Atención de Enfermería', 
                         value = F), 
            numericInput(inputId = 'atn2_45e',   
                       label = 'Número de enfermeros prestando el servicio', 
                       value = NA_integer_),                         
           selectInput(inputId = 'atn2_45eq',
                       label = '¿Cuenta con el equipo para operar el servicio?',
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),


          checkboxInput(inputId = 'atn2_46', 
                         label = 'Estomatología', 
                         value = F), 
          numericInput(inputId = 'atn2_46o',
                       label = 'Número de odontólogos prestando el servicio',
                       value = NA_integer_),
             numericInput(inputId = 'atn2_46me',
                       label = '¿Cuántos médicos especialistas trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_46m',
                       label = '¿Cuántos médicos generales trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_46e',
                       label = '¿Cuántos enfermeros trabajan en el servicio?', 
                       value = NA_integer_),
            selectInput(inputId = 'atn2_46eq', 
                       label = '¿Cuenta con el equipo para operar el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),

           checkboxInput(inputId = 'atn2_47', 
                         label = 'Salud Mental y Adicciones', 
                         value = F), 
           numericInput(inputId = 'atn2_47me',
                       label = '¿Cuántos médicos especialistas trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_47m',
                       label = '¿Cuántos médicos generales trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_47ps',
                       label = '¿Cuántos psicólogos trabajan en el servicio?',
                       value = NA_integer_),
            numericInput(inputId = 'atn2_47e',
                       label = '¿Cuántos enfermeros trabajan en el servicio?', 
                       value = NA_integer_),
            selectInput(inputId = 'atn2_47eq', 
                       label = '¿Cuenta con el equipo para operar el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),

           checkboxInput(inputId = 'atn2_48', 
                         label = 'Trabajo social', 
                         value = F), 
           selectInput(inputId = 'atn2_48eq',
                       label = '¿Cuenta con el equipo para operar el servicio?',
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),
            numericInput(inputId = 'atn2_48t',  
                       label = 'Número de Trabajadores sociales prestando el servicio', 
                       value = NA_integer_),
                 
           checkboxInput(inputId = 'atn2_49', 
                         label = 'Nutrición', 
                         value = F), 
           selectInput(inputId = 'atn2_49eq',
                       label = '¿Cuenta con el equipo para operar el servicio?',
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),
            numericInput(inputId = 'atn2_49n',
                       label = 'Número de Nutriólogos prestando el servicio', 
                       value = NA_integer_),



        
#Asistencia especializada en consultas

           checkboxInput(inputId = 'atn2_50',
                        label = 'Asistencia especializada para consultas (asistente médico)', 
                         value = F), 
           selectInput(inputId = 'atn2_50eq',
                       label = '¿Cuenta con el equipo para operar el servicio?',
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),
            numericInput(inputId = 'atn2_50a', 
                       label = 'Número de asistentes que brindan el servicio', 
                       value = NA_integer_),

#Asistencia especializada en hospitalización (médico y quirúrgicas)

           checkboxInput(inputId = 'atn2_51', 
                        label = 'Asistencia especializada para consultas médico y quirúrgicas (asistente médico)', 
                         value = F), 
           selectInput(inputId = 'atn2_51eq', 
                       label = '¿Cuenta con el equipo para operar el servicio?',
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),
            numericInput(inputId = 'atn2_51a', 
                       label = 'Número de asistentes que brindan el servicio', 
                       value = NA_integer_),

#Atención paliativa a enfermos en fase terminal

           checkboxInput(inputId = 'atn2_52',
                        label = 'Cuidados paliativos', 
                         value = F), 
            numericInput(inputId = 'atn2_52me',
                       label = '¿Cuántos médicos especialistas trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_52m',
                       label = '¿Cuántos médicos generales trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_52e',
                       label = '¿Cuántos enfermeros trabajan en el servicio?', 
                       value = NA_integer_),
            selectInput(inputId = 'atn2_52eq', 
                       label = '¿Cuenta con el equipo para operar el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),

#Especialidades médico-clínicas o clínico-quirúrgicas

           checkboxInput(inputId = 'atn2_53', 
                        label = 'Oncología', 
                         value = F), 
            numericInput(inputId = 'atn2_53me',
                       label = '¿Cuántos médicos especialistas trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_53m',
                       label = '¿Cuántos médicos generales trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_53e',
                       label = '¿Cuántos enfermeros trabajan en el servicio?', 
                       value = NA_integer_),
            selectInput(inputId = 'atn2_53eq', 
                       label = '¿Cuenta con el equipo para operar el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),

           checkboxInput(inputId = 'atn2_54', 
                        label = 'Ginecología y Obstetricia', 
                         value = F), 
            numericInput(inputId = 'atn2_54me',
                       label = '¿Cuántos médicos especialistas trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_54m',
                       label = '¿Cuántos médicos generales trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_54e',
                       label = '¿Cuántos enfermeros trabajan en el servicio?', 
                       value = NA_integer_),
            selectInput(inputId = 'atn2_54eq', 
                       label = '¿Cuenta con el equipo para operar el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),

            checkboxInput(inputId = 'atn2_55',
                        label = 'Pediatría', 
                         value = F),
            numericInput(inputId = 'atn2_55me',
                       label = '¿Cuántos médicos especialistas trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_55m',
                       label = '¿Cuántos médicos generales trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_55e',
                       label = '¿Cuántos enfermeros trabajan en el servicio?', 
                       value = NA_integer_),
            selectInput(inputId = 'atn2_55eq', 
                       label = '¿Cuenta con el equipo para operar el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),

            checkboxInput(inputId = 'atn2_56',
                        label = 'Cirugía General', 
                         value = F), 
           numericInput(inputId = 'atn2_56me',
                       label = '¿Cuántos médicos especialistas trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_56m',
                       label = '¿Cuántos médicos generales trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_56e',
                       label = '¿Cuántos enfermeros trabajan en el servicio?', 
                       value = NA_integer_),
            selectInput(inputId = 'atn2_56eq', 
                       label = '¿Cuenta con el equipo para operar el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),

            checkboxInput(inputId = 'atn2_57',
                        label = 'Medicina Interna', 
                         value = F), 
            numericInput(inputId = 'atn2_57me',
                       label = '¿Cuántos médicos especialistas trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_57m',
                       label = '¿Cuántos médicos generales trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_57e',
                       label = '¿Cuántos enfermeros trabajan en el servicio?', 
                       value = NA_integer_),
            selectInput(inputId = 'atn2_57eq', 
                       label = '¿Cuenta con el equipo para operar el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),


          checkboxInput(inputId = 'atn2_58', 
                        label = 'Psicología', 
                         value = F), 
         numericInput(inputId = 'atn2_58ps',
                       label = '¿Cuántos psicólogos trabajan en el servicio?',
                       value = NA_integer_),
           # numericInput(inputId = 'atn2_59m',
           #            label = '¿Cuántos médicos generales trabajan en el servicio?', 
           #            value = NA_integer_),
           # numericInput(inputId = 'atn2_59e',
           #            label = '¿Cuántos enfermeros trabajan en el servicio?', 
           #            value = NA_integer_),
            selectInput(inputId = 'atn2_58eq', 
                       label = '¿Cuenta con el equipo para operar el servicio?',   #¿aquí sería equipo o insumo?
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),

            checkboxInput(inputId = 'atn2_59', 
                        label = 'Anestesiología', 
                         value = F), 
            numericInput(inputId = 'atn2_59me',
                       label = '¿Cuántos médicos especialistas trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_59m',
                       label = '¿Cuántos médicos generales trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_59e',
                       label = '¿Cuántos enfermeros trabajan en el servicio?', 
                       value = NA_integer_),
            selectInput(inputId = 'atn2_59eq', 
                       label = '¿Cuenta con el equipo para operar el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),

checkboxInput(inputId = 'atn2_60',
                        label = 'Urgencias Médico-Quirúrgicas', 
                         value = F), 
           numericInput(inputId = 'atn2_60me',
                       label = '¿Cuántos médicos especialistas trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_60m',
                       label = '¿Cuántos médicos generales trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_60e',
                       label = '¿Cuántos enfermeros trabajan en el servicio?', 
                       value = NA_integer_),
            selectInput(inputId = 'atn2_60eq', 
                       label = '¿Cuenta con el equipo para operar el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),

#Servicios médico-hospitalarios

           checkboxInput(inputId = 'atn2_61', 
                        label = 'Hospitalización', 
                         value = F), 
            numericInput(inputId = 'atn2_61me',
                       label = '¿Cuántos médicos especialistas trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_61m',
                       label = '¿Cuántos médicos generales trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_61e',
                       label = '¿Cuántos enfermeros trabajan en el servicio?', 
                       value = NA_integer_),
            selectInput(inputId = 'atn2_61eq', 
                       label = '¿Cuenta con el equipo para operar el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),
#####################################SE EDITÓ ESTA VARIABLE NUMERO 63######################################

                 
           checkboxInput(inputId = 'atn2_62',
                        label = 'Cirugía plástica',
                         value = F), 
          numericInput(inputId = 'atn2_62me',
                       label = '¿Cuántos médicos especialistas trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_62m',
                       label = '¿Cuántos médicos generales trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_62e',
                       label = '¿Cuántos enfermeros trabajan en el servicio?', 
                       value = NA_integer_),
            selectInput(inputId = 'atn2_62eq', 
                       label = '¿Cuenta con el equipo para operar el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),

#Servicios médicos de apoyo
           checkboxInput(inputId = 'atn2_63', 
                        label = 'Inhaloterapia', 
                         value = F), 
           numericInput(inputId = 'atn2_63me',
                       label = '¿Cuántos médicos especialistas trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_63m',
                       label = '¿Cuántos médicos generales trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_63e',
                       label = '¿Cuántos enfermeros trabajan en el servicio?', 
                       value = NA_integer_),
            selectInput(inputId = 'atn2_63eq', 
                       label = '¿Cuenta con el equipo para operar el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),



           checkboxInput(inputId = 'atn2_64', 
                        label = 'Clínica de Heridas y Estomas', 
                         value = F), 
              numericInput(inputId = 'atn2_64me',
                       label = 'Número de Médicos especialistas que brindan el servicio?',
                       value = NA_integer_), 
            numericInput(inputId = 'atn2_64m',
                       label = '¿Cuántos médicos generales trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_64e',
                       label = '¿Cuántos enfermeros trabajan en el servicio?', 
                       value = NA_integer_),
            selectInput(inputId = 'atn2_64eq', 
                       label = '¿Cuenta con el equipo para operar el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),

            checkboxInput(inputId = 'atn2_65',
                        label = 'Planificación familiar', 
                         value = F), 
            numericInput(inputId = 'atn2_65me',
                       label = '¿Cuántos médicos especialistas trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_65m',
                       label = '¿Cuántos médicos generales trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_65e',
                       label = '¿Cuántos enfermeros trabajan en el servicio?', 
                       value = NA_integer_),
            selectInput(inputId = 'atn2_65eq', 
                       label = '¿Cuenta con el equipo para operar el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),

#Servicios médicos de apoyo

           checkboxInput(inputId = 'atn2_66', 
                        label = 'Cirugía Ambulatoria',
                         value = F), 
           numericInput(inputId = 'atn2_66me',
                       label = '¿Cuántos médicos especialistas trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_66m',
                       label = '¿Cuántos médicos generales trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_66e',
                       label = '¿Cuántos enfermeros trabajan en el servicio?', 
                       value = NA_integer_),
            selectInput(inputId = 'atn2_66eq', 
                       label = '¿Cuenta con el equipo para operar el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),

            checkboxInput(inputId = 'atn2_67',
                        label = 'Terapia física y rehabilitación',
                         value = F), 
            numericInput(inputId = 'atn2_67me',
                       label = '¿Cuántos médicos especialistas trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_67m',
                       label = '¿Cuántos médicos generales trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_67ft',
                       label = '¿Cuántas fisioterapeutas trabajan en el servicio?',
                       value = NA_integer_),
            numericInput(inputId = 'atn2_67e',
                       label = '¿Cuántos enfermeros trabajan en el servicio?', 
                       value = NA_integer_),
            selectInput(inputId = 'atn2_67eq', 
                       label = '¿Cuenta con el equipo para operar el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),

          checkboxInput(inputId = 'atn2_68', 
                        label = 'Anatomía Patológica',
                         value = F), 
          numericInput(inputId = 'atn2_68me',
                       label = '¿Cuántos médicos especialistas trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_68m',
                       label = '¿Cuántos médicos generales trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_68e',
                       label = '¿Cuántos enfermeros trabajan en el servicio?', 
                       value = NA_integer_),
            selectInput(inputId = 'atn2_68eq', 
                       label = '¿Cuenta con el equipo para operar el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),

#Medicina transfusional
          checkboxInput(inputId = 'atn2_69', 
                        label = 'Medicina transfusional (Banco de sangre, servicio de transfusiones)',
                         value = F), 
          numericInput(inputId = 'atn2_69me',
                       label = '¿Cuántos médicos especialistas trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_69m',
                       label = '¿Cuántos médicos generales trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_69e',
                       label = '¿Cuántos enfermeros trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_69pm',
                       label = 'Total de otro personal que integra el equipo multidisciplinario que trabaja en el servicio',
                       value = NA_integer_),
            selectInput(inputId = 'atn2_69eq', 
                       label = '¿Cuenta con el equipo para operar el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),

#Auxiliares diagnóstico y tratamiento

checkboxInput(inputId = 'atn2_70', 
                         label = 'Ultrasonido', 
                         value = F), 
            numericInput(inputId = 'atn2_70pc',
                       label = 'Total de personal capacitado que puede brindar el servicio (técnicos, radiólogos, etc.)', 
                       value = NA_integer_),                       
            selectInput(inputId = 'atn2_70eq', 
                       label = '¿Cuenta con el equipo para operar el servicio', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),
            numericInput(inputId = 'atn2_70fu', 
                       label = '¿Cuánto equipo es funcional?',
                       value = NA_integer_), 
            numericInput(inputId = 'atn2_70nf', 
                       label = '¿Cuánto equipo no es funcional?',
                       value = NA_integer_),


           checkboxInput(inputId = 'atn2_71', 
                        label = 'Mastógrafo',
                         value = F), 
          numericInput(inputId = 'atn2_71pc',
                       label = 'Total de personal capacitado que puede brindar el servicio (técnicos, radiólogos, etc.)', 
                       value = NA_integer_),                       
            selectInput(inputId = 'atn2_71eq', 
                       label = '¿Cuenta con el equipo para operar el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),
            numericInput(inputId = 'atn2_71fu', 
                       label = '¿Cuánto equipo es funcional?',
                       value = NA_integer_), 
            numericInput(inputId = 'atn2_71nf', 
                       label = '¿Cuánto equipo no es funcional?',
                       value = NA_integer_),

          checkboxInput(inputId = 'atn2_72',    
                        label = 'USG DOPPLER',
                         value = F), 
          numericInput(inputId = 'atn2_72pc',
                       label = 'Total de personal capacitado que puede brindar el servicio (técnicos, radiólogos, etc.)', 
                       value = NA_integer_),                       
            selectInput(inputId = 'atn2_72eq', 
                       label = '¿Cuenta con el equipo para operar el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),
            numericInput(inputId = 'atn2_72fu', 
                       label = '¿Cuánto equipo es funcional?',
                       value = NA_integer_), 
            numericInput(inputId = 'atn2_72nf', 
                       label = '¿Cuánto equipo no es funcional?',
                       value = NA_integer_),

           checkboxInput(inputId = 'atn2_73', 
                        label = 'Tomografía',
                         value = F), 
          numericInput(inputId = 'atn2_73pc',
                       label = 'Total de personal capacitado que puede brindar el servicio (técnicos, radiólogos, etc.)', 
                       value = NA_integer_),                       
            selectInput(inputId = 'atn2_73eq', 
                       label = '¿Cuenta con el equipo para operar el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),
            numericInput(inputId = 'atn2_73fu', 
                       label = '¿Cuánto equipo es funcional?',
                       value = NA_integer_), 
            numericInput(inputId = 'atn2_73nf', 
                       label = '¿Cuánto equipo no es funcional?',
                       value = NA_integer_),

           checkboxInput(inputId = 'atn2_74', 
                        label = 'Resonancia magnética',
                         value = F), 
          numericInput(inputId = 'atn2_74pc',
                       label = 'Total de personal capacitado que puede brindar el servicio (técnicos, radiólogos, etc.)', 
                       value = NA_integer_),                       
            selectInput(inputId = 'atn2_74eq', 
                       label = '¿Cuenta con el equipo para operar el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),
            numericInput(inputId = 'atn2_74fu', 
                       label = '¿Cuánto equipo es funcional?',
                       value = NA_integer_), 
            numericInput(inputId = 'atn2_74nf', 
                       label = '¿Cuánto equipo no es funcional?',
                       value = NA_integer_),

  checkboxInput(inputId = 'atn2_75', 
                        label = 'Endoscopía',
                         value = F), 
         numericInput(inputId = 'atn2_75pc',
                       label = 'Total de personal capacitado que puede brindar el servicio (técnicos, radiólogos, etc.)', 
                       value = NA_integer_),                       
            selectInput(inputId = 'atn2_75eq', 
                       label = '¿Cuenta con el equipo para operar el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),
            numericInput(inputId = 'atn2_75fu', 
                       label = '¿Cuánto equipo es funcional?',
                       value = NA_integer_), 
            numericInput(inputId = 'atn2_75nf', 
                       label = '¿Cuánto equipo no es funcional?',
                       value = NA_integer_),

         checkboxInput(inputId = 'atn2_76', 
                         label = 'Espirometría', 
                         value = F), 
            numericInput(inputId = 'atn2_76me',
                       label = '¿Cuántos médicos especialistas trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_76m',
                       label = '¿Cuántos médicos generales trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_76e',
                       label = '¿Cuántos enfermeros trabajan en el servicio?', 
                       value = NA_integer_),
            selectInput(inputId = 'atn2_76eq', 
                       label = '¿Cuenta con el equipo para operar el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),
            numericInput(inputId = 'atn2_76es', 
                       label = '¿Cuántos equipos de espirometría se cuentan en el servicio?',
                       value = NA_integer_),                        
            numericInput(inputId = 'atn2_76fu', 
                       label = '¿Cuánto equipo es funcional?',
                       value = NA_integer_), 
            numericInput(inputId = 'atn2_76nf', 
                       label = '¿Cuánto equipo no es funcional?',
                       value = NA_integer_),

           checkboxInput(inputId = 'atn2_77',
                        label = 'Electroencefalograma',
                         value = F), 
             numericInput(inputId = 'atn2_77me',
                       label = '¿Cuántos médicos especialistas trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_77m',
                       label = '¿Cuántos médicos generales trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_77e',
                       label = '¿Cuántos enfermeros trabajan en el servicio?', 
                       value = NA_integer_),
            selectInput(inputId = 'atn2_77eq',
                       label = '¿Cuenta con el equipo para operar el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),
            numericInput(inputId = 'atn2_77es', 
                       label = '¿Cuántos equipos de electro-encefalograma hay en el servicio?',
                       value = NA_integer_),                        
            numericInput(inputId = 'atn2_77fu', 
                       label = '¿Cuánto equipo es funcional?',
                       value = NA_integer_), 
            numericInput(inputId = 'atn2_77nf', 
                       label = '¿Cuánto equipo no es funcional?',
                       value = NA_integer_),

           checkboxInput(inputId = 'atn2_78', 
                        label = 'Hemodinamia',
                        value = F), 
           numericInput(inputId = 'atn2_78pc',
                       label = 'Total de personal capacitado que puede brindar el servicio', 
                       value = NA_integer_),                       
            selectInput(inputId = 'atn2_78eq', 
                       label = '¿Cuenta con el equipo para operar el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),
            numericInput(inputId = 'atn2_78fu', 
                       label = '¿Cuánto equipo es funcional?',
                       value = NA_integer_), 
            numericInput(inputId = 'atn2_78nf', 
                       label = '¿Cuánto equipo no es funcional?',
                       value = NA_integer_),

checkboxInput(inputId = 'atn2_79',
                        label = 'Diálisis y Hemodiálisis',
                         value = F), 
          numericInput(inputId = 'atn2_79pc',
                       label = 'Total de personal capacitado que puede brindar el servicio', 
                       value = NA_integer_),                       
            selectInput(inputId = 'atn2_79eq', 
                       label = '¿Cuenta con el equipo para operar el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),
            numericInput(inputId = 'atn2_79fu', 
                       label = '¿Cuánto equipo es funcional?',
                       value = NA_integer_), 
            numericInput(inputId = 'atn2_79nf', 
                       label = '¿Cuánto equipo no es funcional?',
                       value = NA_integer_),

         checkboxInput(inputId = 'atn2_80', 
                        label = 'Audiología y Foniatría',
                         value = F), 
            numericInput(inputId = 'atn2_80me',
                       label = '¿Cuántos médicos especialistas trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_80m',
                       label = '¿Cuántos médicos generales trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_80e',
                       label = '¿Cuántos enfermeros trabajan en el servicio?', 
                       value = NA_integer_),
            selectInput(inputId = 'atn2_80eq',
                       label = '¿Cuenta con el equipo para operar el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),
            numericInput(inputId = 'atn2_80aud', 
                       label = '¿Cuánto equipos de electro de audiología y foniatría hay en el servicio?',
                       value = NA_integer_),                        
            numericInput(inputId = 'atn2_80fu', 
                       label = '¿Cuánto equipo es funcional?',
                       value = NA_integer_), 
            numericInput(inputId = 'atn2_80nf', 
                       label = '¿Cuánto equipo no es funcional?',
                       value = NA_integer_),

           checkboxInput(inputId = 'atn2_81', 
                        label = 'Ecocardiograma',
                         value = F), 
         numericInput(inputId = 'atn2_81me',
                       label = '¿Cuántos médicos especialistas trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_81m',
                       label = '¿Cuántos médicos generales trabajan en el servicio?', 
                       value = NA_integer_),
            numericInput(inputId = 'atn2_81e',
                       label = '¿Cuántos enfermeros trabajan en el servicio?', 
                       value = NA_integer_),
            selectInput(inputId = 'atn2_81eq',
                       label = '¿Cuenta con el equipo para operar el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),
            numericInput(inputId = 'atn2_81ec', 
                       label = '¿Cuántos equipos de ecocardiograma hay en el servicio?',
                       value = NA_integer_),                        
            numericInput(inputId = 'atn2_81fu', 
                       label = '¿Cuánto equipo es funcional?',
                       value = NA_integer_), 
            numericInput(inputId = 'atn2_81nf', 
                       label = '¿Cuánto equipo no es funcional?',
                       value = NA_integer_),

            checkboxInput(inputId = 'atn2_82', 
                         label = 'GeneXpert', 
                         value = F), 
            numericInput(inputId = 'atn2_82pc',
                       label = 'Total de personal capacitado que puede brindar el servicio (técnicos, radiólogos, etc.)', 
                       value = NA_integer_),                       
            selectInput(inputId = 'atn2_82eq', 
                       label = '¿Cuenta con el equipo para operar el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),
            numericInput(inputId = 'atn2_82fu', 
                       label = '¿Cuánto equipo es funcional?',
                       value = NA_integer_), 
            numericInput(inputId = 'atn2_82nf', 
                       label = '¿Cuánto equipo no es funcional?',
                       value = NA_integer_),
                       
                       
 ###Servicios faltantes############################################################################################################################################
### SE AÑADIERON ESTAS NUEVAS VARIABLES#######################################################################################################
            checkboxInput(inputId = 'atn2_83', 
                        label = 'Estimulación temprana',
                         value = F),
            numericInput(inputId = 'atn2_83m', 
                        label = '¿Cuantos médicos hay en este servicio?', 
                        value = NA_integer_), 
            numericInput(inputId = 'atn2_83e', 
                        label = '¿Cuántos enfermeros hay en este servicio?',
                        value = NA_integer_),
            selectInput(inputId = 'atn2_83i', 
                       label = '¿Cuenta con el insumo para operar el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),                         

            checkboxInput(inputId = 'atn2_84', 
                        label = 'Vacunación universal',
                         value = F),
 ##Menú para seleccionar las de vacunas disponibles en el servicio (BCG, Hepatitis B, Hexavalente 'DPaT+VPI+Hib+HepB', DPT, Rotavirus, Neumocócica conjugada, SRP, Influenza, Covid-19, VPH)
            numericInput(inputId = 'atn2_84m', 
                        label = '¿Cuantos médicos hay en este servicio?', 
                        value = NA_integer_), 
            numericInput(inputId = 'atn2_84e', 
                        label = '¿Cuántos enfermeros hay en este servicio?',
                        value = NA_integer_),
            selectInput(inputId = 'atn2_84i', 
                       label = '¿Cuenta con el insumo para operar el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),
            selectInput(inputId = 'atn2_84rf', 
                       label = '¿Cuenta red de frío en el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),                                               
            selectInput(inputId = 'atn2_84i', 
                       label = '¿Cuenta con el insumo para operar el servicio?', 
                       choices = c('BCG', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),        

            checkboxInput(inputId = 'atn2_85', 
                        label = 'Estimulación temprana',
                         value = F),
            numericInput(inputId = 'atn2_85m', 
                        label = '¿Cuantos médicos hay en este servicio?', 
                        value = NA_integer_), 
            numericInput(inputId = 'atn2_85e', 
                        label = '¿Cuántos enfermeros hay en este servicio?',
                        value = NA_integer_),
            selectInput(inputId = 'atn2_85i', 
                       label = '¿Cuenta con el insumo para operar el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),   

            checkboxInput(inputId = 'atn2_86', 
                        label = 'Unidad de terapia intermedia',
                         value = F),
            numericInput(inputId = 'atn2_86m', 
                        label = '¿Cuantos médicos hay en este servicio?', 
                        value = NA_integer_), 
            numericInput(inputId = 'atn2_86e', 
                        label = '¿Cuántos enfermeros hay en este servicio?',
                        value = NA_integer_),
            selectInput(inputId = 'atn2_86i', 
                       label = '¿Cuenta con el insumo para operar el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),   

            checkboxInput(inputId = 'atn2_87', 
                        label = 'Epidemiología',
                         value = F),
            numericInput(inputId = 'atn2_87m', 
                        label = '¿Cuantos médicos hay en este servicio?', 
                        value = NA_integer_), 
            numericInput(inputId = 'atn2_87e', 
                        label = '¿Cuántos enfermeros hay en este servicio?',
                        value = NA_integer_),
            selectInput(inputId = 'atn2_87i', 
                       label = '¿Cuenta con el insumo para operar el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA'),                                                                                      

            checkboxInput(inputId = 'atn2_88', 
                        label = 'Infectología',
                         value = F),
            numericInput(inputId = 'atn2_88m', 
                        label = '¿Cuantos médicos hay en este servicio?', 
                        value = NA_integer_), 
            numericInput(inputId = 'atn2_88e', 
                        label = '¿Cuántos enfermeros hay en este servicio?',
                        value = NA_integer_),
            selectInput(inputId = 'atn2_88i', 
                       label = '¿Cuenta con el insumo para operar el servicio?', 
                       choices = c('Si', 'No', 'Parcial', 'NA'), 
                       selected = 'NA')
)
